common/models/CheckInOut.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "check_in_out".
 *
 * @property int $id
 * @property string $absen_id
 * @property string $tgl_absen
 * @property string $jam_absen
 * @property string $cabang_id
 * @property string $created_at
 */
class CheckInOut extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'check_in_out';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['absen_id', 'tgl_absen', 'jam_absen', 'cabang_id', 'created_at'], 'required'],
            [['tgl_absen', 'jam_absen', 'created_at'], 'safe'],
            [['absen_id'], 'string', 'max' => 255],
            [['cabang_id'], 'string', 'max' => 50],
            [['absen_id', 'tgl_absen', 'jam_absen'], 'unique', 'targetAttribute' => ['absen_id', 'tgl_absen', 'jam_absen']]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'absen_id' => 'Absen ID',
            'tgl_absen' => 'Tgl Absen',
            'jam_absen' => 'Jam Absen',
            'cabang_id' => 'Cabang ID',
            'created_at' => 'Created At',
        ];
    }

    public function getPegawai(){
        return $this->hasOne(Profile::className(),['absensi_id'=>'absen_id']);
    }

    public static function calculateFaceDistance($descriptor1, $descriptor2)
    {
        // Implementasikan algoritma perhitungan jarak antara dua descriptor wajah
        $distance = 0;
        for ($i = 0; $i < count($descriptor1); $i++) {
            $distance += pow($descriptor1[$i] - $descriptor2[$i], 2);
        }
        return sqrt($distance);
    }

    public static function compressImage($source, $destination, $maxSize)
    {
        $quality = 90; // Awalnya kualitas tinggi
        do {
            // Buat versi terkompresi
            $image = imagecreatefrompng($source);
            ob_start();
            imagepng($image, null, round($quality / 10)); // Kompresi untuk PNG
            $compressedData = ob_get_clean();
            imagedestroy($image);

            // Cek ukuran
            if (strlen($compressedData) <= $maxSize || $quality <= 10) {
                file_put_contents($destination, $compressedData);
                return true;
            }

            // Kurangi kualitas
            $quality -= 10;
        } while ($quality > 0);

        return false; // Jika gagal mencapai ukuran
    }

}

backend/controllers/CheckInOutController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\CheckInOut;
use common\models\CheckInOutSearch;
use common\models\FaceUser;
use common\models\Profile;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\Response;

/**
 * CheckInOutController implements the CRUD actions for CheckInOut model.
 */
class CheckInOutController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CheckInOut models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CheckInOutSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single CheckInOut model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CheckInOut model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CheckInOut();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing CheckInOut model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionAttendance(){
        return $this->render('attendance');
    }

    public function actionMatchFace()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        // Ambil data dari request
        $postData = Yii::$app->request->getRawBody();
        $data = json_decode($postData, true);

        // Debug untuk memeriksa data yang diterima
        Yii::info('Data yang diterima: ' . print_r($data, true));

        if (!isset($data['descriptor'])) {
            return ['success' => false, 'message' => 'Descriptor wajah tidak ditemukan'];
        }

        $descriptor = $data['descriptor'];

        // Ambil profil dari database dan bandingkan
        $profiles = FaceUser::find()->all();
        $matchedProfileId = null;
        foreach ($profiles as $profile) {
            $storedDescriptor = json_decode($profile->face_decrypt, true);

            // Pastikan descriptor yang disimpan tidak null
            if (!$storedDescriptor) {
                continue;
            }

            // Bandingkan descriptor wajah
            $distance = CheckInOut::calculateFaceDistance($descriptor, $storedDescriptor);
            if ($distance < 0.3) {  // Toleransi untuk kecocokan wajah
                $matchedProfileId = $profile->profile_id;
                break;
            }
        }

        if ($matchedProfileId) {
            return ['success' => true, 'profileId' => $matchedProfileId];

        }

        return ['success' => false, 'message' => 'Wajah tidak cocok atau tidak ditemukan'];
        
    }


    public function actionRecordAttendance()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        
        // Ambil data yang dikirim melalui POST
        $postData = Yii::$app->request->post();
        
        // Debug untuk memeriksa data yang diterima
        Yii::info('Data yang diterima: ' . print_r($postData, true));

        // Pastikan data yang diterima valid
        if (!isset($postData['profile_id'])) {

            Yii::$app->getSession()->setFlash('success', [
                'type' => 'danger',
                'duration' => 3000,
                'icon' => 'fa fa-close',
                'message' => Yii::t('app',Html::encode('Face Not Found.!')),
                'title' => Yii::t('app', Html::encode('Face Attendance.')),
                'positonY' => 'top',
                'positonX' => 'right', 
            ]);

            return $this->redirect(['attendance']);
        }
        
        if (!isset($postData['image_data'])) {

            Yii::$app->getSession()->setFlash('success', [
                'type' => 'danger',
                'duration' => 3000,
                'icon' => 'fa fa-close',
                'message' => Yii::t('app',Html::encode('Image Not Found.!')),
                'title' => Yii::t('app', Html::encode('Face Attendance.')),
                'positonY' => 'top',
                'positonX' => 'right', 
            ]);

            return $this->redirect(['attendance']);
        }

        // Ambil data profile_id dan image_data
        $profileId = $postData['profile_id'];
        $imageData = $postData['image_data'];
        $outletId = $postData['outlet_id'];

        // Proses lebih lanjut, seperti menyimpan ke database

        $dataPegawai = Profile::findOne($profileId);

        $attLog = new CheckInOut();
        $attLog->absen_id = $dataPegawai->absensi_id;
        $attLog->tgl_absen = date('Y-m-d');
        $attLog->jam_absen = date('H:i:s');
        $attLog->cabang_id = 'DOT'.$outletId;
        $attLog->created_at = date('Y-m-d');

        if ($attLog->save()) {

            // Decode base64 image
            $imageData = str_replace('data:image/png;base64,', '', $imageData);
            $imageData = str_replace(' ', '+', $imageData);
            $decodedData = base64_decode($imageData);

             // Tentukan path untuk menyimpan file
            $filePath = Yii::getAlias('@backend/web/uploads/attendance_photos/');
            if (!file_exists($filePath)) {
                mkdir($filePath, 0777, true);
            }
            $fileName = $filePath . $attLog->id . '.png';

            file_put_contents($fileName, $decodedData);

            // Kompres gambar
            $compressedFileName = $filePath . $attLog->id . '_compressed.png';
            CheckInOut::compressImage($fileName, $compressedFileName, 100 * 1024); // Target 100 KB

            // Hapus file asli jika kompresi berhasil
            if (file_exists($compressedFileName)) {
                unlink($fileName);
                $fileName = $compressedFileName;
            }

            Yii::$app->getSession()->setFlash('success', [
                'type' => 'success',
                'duration' => 3000,
                'icon' => 'fa fa-close',
                'message' => Yii::t('app',Html::encode('Log attendance success.!')),
                'title' => Yii::t('app', Html::encode('Face Attendance.')),
                'positonY' => 'top',
                'positonX' => 'right', 
            ]);

            return $this->redirect(['attendance-success', 'id' => $attLog->id]);

        } else {
            
            Yii::$app->getSession()->setFlash('success', [
                'type' => 'danger',
                'duration' => 3000,
                'icon' => 'fa fa-close',
                'message' => Yii::t('app',Html::encode('Log attendance failed.!')),
                'title' => Yii::t('app', Html::encode('Face Attendance.')),
                'positonY' => 'top',
                'positonX' => 'right', 
            ]);

            return $this->redirect(['attendance']);

        }
    }
    
    public function actionAttendanceSuccess($id){
        $dataLog = CheckInOut::findOne($id);
        return $this->render('attendance-success', [
            'dataLog' => $dataLog
        ]);
    }

    /**
     * Deletes an existing CheckInOut model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CheckInOut model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CheckInOut the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CheckInOut::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/check-in-out/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CheckInOut */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="check-in-out-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'absen_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tgl_absen')->textInput() ?>

    <?= $form->field($model, 'jam_absen')->textInput() ?>

    <?= $form->field($model, 'cabang_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/check-in-out/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CheckInOutSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="check-in-out-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'absen_id') ?>

    <?= $form->field($model, 'tgl_absen') ?>

    <?= $form->field($model, 'jam_absen') ?>

    <?= $form->field($model, 'cabang_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/check-in-out/attendance-success.php
<?php

use common\models\Profile;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Attendance';
$this->params['breadcrumbs'][] = $this->title;

$csrfToken = Yii::$app->request->csrfToken;
?>

<div class="row">
    <div class="col-lg-4">
       <div class="box box-info">
            <div class="box-body">
                <table class="table table-striped">
                    <tr>
                        <th>Nama Pegawai</th>
                        <td><?= $dataLog->pegawai->nama; ?></td>
                    </tr>
                    <tr>
                        <th>Outlet</th>
                        <td><?= $dataLog->cabang_id ?></td>
                    </tr>
                    <tr>
                        <th>Tgl. Absen</th>
                        <td><?= Yii::$app->formatter->asDate($dataLog->tgl_absen); ?></td>
                    </tr>
                    <tr>
                        <th>Jam Absen</th>
                        <td><?= $dataLog->jam_absen; ?></td>
                    </tr>
                </table>
            </div>
       </div>
    </div>
    <div class="col-lg-8">
        <div class="box box-success">
            <div class="box-body">
                <?php if(Profile::myCabang() == "Outlet Not Set"){
                ?>
                <h1 align="center">Outlet For This Account Not Set Yet.</h1>
                <?php
                }
                else{
                    $cabangActive = Profile::myProfile2()->cabangActive;
                ?>
                <h3>Outlet : <?= Profile::myCabang(); ?></h3>
                <strong id="display-distance"></strong>
                <p>Activate the camera to use the attendance.</p>

                <center>
                    <video id="video" autoplay muted></video>
                </center>
                
                <button id="capture" class="btn btn-success btn-icon-split btn-block">
                    <span class="icon text-white-50"><i class="fas fa-camera"></i></span>
                    <span class="text"> Capture & Save</span>
                </button>

                <canvas id="snapshot" style="display: none;"></canvas>

                <?= Html::beginForm(['/check-in-out/record-attendance'], 'post', ['id' => 'attendance-form']) ?>
                    <?= Html::hiddenInput('outlet_id', $cabangActive->id_cabang, ['id' => 'outlet-id']) ?>
                    <?= Html::hiddenInput('image_data', '', ['id' => 'image-data']) ?>
                    <?= Html::hiddenInput('profile_id', '',  ['id' => 'profile-id']) ?>
                <?= Html::endForm() ?>

                <?php } ?>
            </div>
        </div>
    </div>
</div>

<?php
$this->registerJsFile('/js/face-api/dist/face-api.js', ['position' => \yii\web\View::POS_HEAD]);

$script = <<<JS
const video = document.getElementById('video');
const snapshot = document.getElementById('snapshot');
const imageDataInput = document.getElementById('image-data');
const profileIdInput = document.getElementById('profile-id');
const outletIdInput = document.getElementById('outlet-id');

// Load models
Promise.all([
    faceapi.nets.tinyFaceDetector.loadFromUri('/js/face-api/weights'),
    faceapi.nets.faceLandmark68Net.loadFromUri('/js/face-api/weights'),
    faceapi.nets.faceRecognitionNet.loadFromUri('/js/face-api/weights'),
]).then(startVideo);

// Start webcam
function startVideo() {
    navigator.mediaDevices.getUserMedia({ video: {} })
        .then(stream => video.srcObject = stream)
        .catch(err => console.error(err));
}

// Capture image and match face
document.getElementById('capture').addEventListener('click', async () => {
    const detection = await faceapi.detectSingleFace(video, new faceapi.TinyFaceDetectorOptions())
        .withFaceLandmarks()
        .withFaceDescriptor();

    if (detection) {
        const descriptor = detection.descriptor;
        
        // Send descriptor to server to match face
        const response = await fetch('/check-in-out/match-face', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-Token': '<?= $csrfToken ?>'
            },
            body: JSON.stringify({ descriptor })
        });

        const result = await response.json();


        if (result.success) {
            // If face matched, save profile_id for attendance
            profileIdInput.value = result.profileId;

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);

            // Konversi gambar ke data URL
            const imageDataUrl = canvas.toDataURL('image/png');

            imageDataInput.value = imageDataUrl;

            // Submit attendance form
            document.getElementById('attendance-form').submit();
            
        } else {
            alert('Wajah tidak terdeteksi atau tidak cocok');
        }
    } else {
        alert('Wajah tidak terdeteksi. Pastikan kamera mengarah ke wajah Anda.');
    }
});


    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
    } else {
        alert("Geolocation is not supported by this browser.");
    }

    function showPosition(position) {
        const latitude = position.coords.latitude;
        const longitude = position.coords.longitude;
        const latitude1 = $cabangActive->latitude;
        const longitude1 = $cabangActive->longitude;

        let distance = haversine(latitude1, longitude, latitude, longitude);

        if(distance > 1){
            document.getElementById("capture").disabled = true;
            document.getElementById('display-distance').innerHTML = "Distance with Outlet too Far : " + distance.toFixed(2) + " km.";
            document.getElementById('display-distance').className = "text-danger";
        }
        else{
            document.getElementById('display-distance').innerHTML = "Distance with Outlet : " + distance.toFixed(2)*1000 + " mtr.";
            document.getElementById('display-distance').className = "text-success";
        }

    }

    function haversine(lat1, lon1, lat2, lon2, unit = "km") {
        const toRadian = angle => (Math.PI / 180) * angle;
        const earthRadius = unit === "km" ? 6371 : 3958.8; // Radius bumi: km atau mil

        const deltaLat = toRadian(lat2 - lat1);
        const deltaLon = toRadian(lon2 - lon1);

        const a = Math.sin(deltaLat / 2) ** 2 +
                Math.cos(toRadian(lat1)) * Math.cos(toRadian(lat2)) *
                Math.sin(deltaLon / 2) ** 2;

        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

        return earthRadius * c; // Jarak dalam unit yang dipilih
    }


    function showError(error) {
        switch (error.code) {
            case error.PERMISSION_DENIED:
                alert("User denied the request for Geolocation.");
                break;
            case error.POSITION_UNAVAILABLE:
                alert("Location information is unavailable.");
                break;
            case error.TIMEOUT:
                alert("The request to get user location timed out.");
                break;
            case error.UNKNOWN_ERROR:
                alert("An unknown error occurred.");
                break;
        }
    }

JS;

$this->registerJs($script);
?>

backend/views/check-in-out/attendance.php
<?php

use common\models\Profile;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Attendance';
$this->params['breadcrumbs'][] = $this->title;

$csrfToken = Yii::$app->request->csrfToken;
?>

<div class="box box-success">
    <div class="box-body">
        <?php if(Profile::myCabang() == "Outlet Not Set"){
        ?>
        <h1 align="center">Outlet For This Account Not Set Yet.</h1>
        <?php
        }
        else{
            $cabangActive = Profile::myProfile2()->cabangActive;
        ?>
        <h3>Outlet : <?= Profile::myCabang(); ?></h3>
        <strong id="display-distance"></strong>
        <p>Activate the camera to use the attendance.</p>

        <center>
            <video id="video" autoplay muted></video>
        </center>
        
        <button id="capture" class="btn btn-success btn-icon-split btn-block">
            <span class="icon text-white-50"><i class="fas fa-camera"></i></span>
            <span class="text"> Capture & Save</span>
        </button>

        <canvas id="snapshot" style="display: none;"></canvas>

        <?= Html::beginForm(['/check-in-out/record-attendance'], 'post', ['id' => 'attendance-form']) ?>
            <?= Html::hiddenInput('outlet_id', $cabangActive->id_cabang, ['id' => 'outlet-id']) ?>
            <?= Html::hiddenInput('image_data', '', ['id' => 'image-data']) ?>
            <?= Html::hiddenInput('profile_id', '',  ['id' => 'profile-id']) ?>
        <?= Html::endForm() ?>

        <?php } ?>
    </div>
</div>

<?php
$this->registerJsFile('/js/face-api/dist/face-api.js', ['position' => \yii\web\View::POS_HEAD]);

$script = <<<JS
const video = document.getElementById('video');
const snapshot = document.getElementById('snapshot');
const imageDataInput = document.getElementById('image-data');
const profileIdInput = document.getElementById('profile-id');
const outletIdInput = document.getElementById('outlet-id');

// Load models
Promise.all([
    faceapi.nets.tinyFaceDetector.loadFromUri('/js/face-api/weights'),
    faceapi.nets.faceLandmark68Net.loadFromUri('/js/face-api/weights'),
    faceapi.nets.faceRecognitionNet.loadFromUri('/js/face-api/weights'),
]).then(startVideo);

// Start webcam
function startVideo() {
    navigator.mediaDevices.getUserMedia({ video: {} })
        .then(stream => video.srcObject = stream)
        .catch(err => console.error(err));
}

// Capture image and match face
document.getElementById('capture').addEventListener('click', async () => {
    const detection = await faceapi.detectSingleFace(video, new faceapi.TinyFaceDetectorOptions())
        .withFaceLandmarks()
        .withFaceDescriptor();

    if (detection) {
        const descriptor = detection.descriptor;
        
        // Send descriptor to server to match face
        const response = await fetch('/check-in-out/match-face', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-Token': '<?= $csrfToken ?>'
            },
            body: JSON.stringify({ descriptor })
        });

        const result = await response.json();


        if (result.success) {
            // If face matched, save profile_id for attendance
            profileIdInput.value = result.profileId;

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);

            // Konversi gambar ke data URL
            const imageDataUrl = canvas.toDataURL('image/png');

            imageDataInput.value = imageDataUrl;

            // Submit attendance form
            document.getElementById('attendance-form').submit();
            
        } else {
            alert('Wajah tidak terdeteksi atau tidak cocok');
        }
    } else {
        alert('Wajah tidak terdeteksi. Pastikan kamera mengarah ke wajah Anda.');
    }
});


    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
    } else {
        alert("Geolocation is not supported by this browser.");
    }

    function showPosition(position) {
        const latitude = position.coords.latitude;
        const longitude = position.coords.longitude;
        const latitude1 = $cabangActive->latitude;
        const longitude1 = $cabangActive->longitude;

        let distance = haversine(latitude1, longitude, latitude, longitude);

        if(distance > 1){
            document.getElementById("capture").disabled = true;
            document.getElementById('display-distance').innerHTML = "Distance with Outlet too Far : " + distance.toFixed(2) + " km.";
            document.getElementById('display-distance').className = "text-danger";
        }
        else{
            document.getElementById('display-distance').innerHTML = "Distance with Outlet : " + distance.toFixed(2)*1000 + " mtr.";
            document.getElementById('display-distance').className = "text-success";
        }

    }

    function haversine(lat1, lon1, lat2, lon2, unit = "km") {
        const toRadian = angle => (Math.PI / 180) * angle;
        const earthRadius = unit === "km" ? 6371 : 3958.8; // Radius bumi: km atau mil

        const deltaLat = toRadian(lat2 - lat1);
        const deltaLon = toRadian(lon2 - lon1);

        const a = Math.sin(deltaLat / 2) ** 2 +
                Math.cos(toRadian(lat1)) * Math.cos(toRadian(lat2)) *
                Math.sin(deltaLon / 2) ** 2;

        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

        return earthRadius * c; // Jarak dalam unit yang dipilih
    }


    function showError(error) {
        switch (error.code) {
            case error.PERMISSION_DENIED:
                alert("User denied the request for Geolocation.");
                break;
            case error.POSITION_UNAVAILABLE:
                alert("Location information is unavailable.");
                break;
            case error.TIMEOUT:
                alert("The request to get user location timed out.");
                break;
            case error.UNKNOWN_ERROR:
                alert("An unknown error occurred.");
                break;
        }
    }

JS;

$this->registerJs($script);
?>

backend/views/check-in-out/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\CheckInOut */

$this->title = 'Create Check In Out';
$this->params['breadcrumbs'][] = ['label' => 'Check In Outs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="check-in-out-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/check-in-out/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\CheckInOut */

$this->title = 'Update Check In Out: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Check In Outs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="check-in-out-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/check-in-out/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\CheckInOut */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Check In Outs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="check-in-out-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'absen_id',
            'tgl_absen',
            'jam_absen',
            'cabang_id',
            'created_at',
        ],
    ]) ?>

</div>