common/models/Barang.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "barang".
 *
 * @property int $id_barang
 * @property string $no_kontrak
 * @property int $id_nasabah
 * @property string $nama_barang
 * @property string $merk
 * @property string $tipe
 * @property string $serial
 * @property int $id_jenis
 * @property string $tgl_masuk
 * @property string $jatuh_tempo
 * @property string $spek
 * @property string $kelengkapan
 * @property string $kondisi
 * @property int $harga_pasar
 * @property int $harga_taksir
 * @property int $nilai_pinjam
 * @property float $bunga
 * @property int $biaya_admin
 * @property int|null $biaya_simpan
 * @property int $jangka
 * @property int $created_by
 * @property string $status
 * @property int $id_cabang
 * @property string $kata_sandi
 *
 * @property Cabang $cabang
 * @property LogStatus[] $logStatuses
 * @property LogStatusTemp[] $logStatusTemps
 * @property TambahanJual[] $tambahanJuals
 */
class Barang extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'barang';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['no_kontrak', 'id_nasabah', 'nama_barang', 'merk', 'tipe', 'serial', 'id_jenis', 'tgl_masuk', 'jatuh_tempo', 'spek', 'kelengkapan', 'kondisi', 'harga_pasar', 'harga_taksir', 'nilai_pinjam', 'bunga', 'biaya_admin', 'jangka', 'created_by', 'status', 'id_cabang', 'no_fak', 'kata_sandi'], 'required'],
            [['id_nasabah', 'id_jenis', 'harga_pasar', 'harga_taksir', 'nilai_pinjam', 'biaya_admin', 'biaya_simpan', 'jangka', 'created_by', 'id_cabang', 'lokasi_simpan_id'], 'integer'],
            [['tgl_masuk', 'jatuh_tempo', 'tgl_status'], 'safe'],
            [['spek', 'kelengkapan', 'kondisi'], 'string'],
            [['bunga'], 'double'],
            [['no_kontrak', 'nama_barang', 'merk', 'tipe', 'serial', 'status'], 'string', 'max' => 225],
            [['id_cabang'], 'exist', 'skipOnError' => true, 'targetClass' => Cabang::className(), 'targetAttribute' => ['id_cabang' => 'id_cabang']],

            ['nilai_pinjam', 'compare', 'compareAttribute' => 'harga_pasar', 'operator' => '<', 'type' => 'number', 'message' => 'Nilai Pinjam harus dibawah Harga Pasar.'],

            [['serial', 'spek', 'kelengkapan', 'kondisi'], 'compare', 'compareValue' => '-', 'operator' => '!==', 'message' => 'Isi Data Ini dengan Benar'],

            ['nilai_pinjam', 'match', 'pattern' => '/^\d*000$/', 'message' => 'Nilai ini harus berkelipatan 1000.'],

        ];
    }

    public static function noKontrak(){
        $maxid = Barang::find()->orderBy(['id_barang' => SORT_DESC])->one();
        $id_cabang = Yii::$app->session['id_cabang'];
        $no_kontrak = date('Ym').$maxid->id_barang;
        $no_kontrak = $no_kontrak + 1;
        $no_kontrak = $no_kontrak.rand(0,9).$id_cabang;

        return $no_kontrak;
    }

    public static function noKontrakLangsung($tgl,$cabang){
        $maxid = Barang::find()->where(['tgl_masuk' => $tgl])->orderBy(['id_barang' => SORT_DESC])->one();
        if(empty($maxid->no_kontrak)){
            $no_kontrak = date_format(date_create($tgl),'Ym')."1001".$cabang;
        }
        else{
            $no_kontrak = $maxid->no_kontrak+1;
            $no_kontrak = $no_kontrak.$cabang;
        }
        return $no_kontrak;
    }

    public function getBarang(){
        return $this->hasOne(Profile::className(),['id_user'=>'id_nasabah']);
    }

    public function getNasabah(){
        return $this->hasOne(Profile::className(),['id_user'=>'id_nasabah']);
    }

    public function getCreatedBy(){
        return $this->hasOne(Profile::className(),['id_user'=>'created_by']);
    }

    public function myNasabah(){
        $id_nasabah = $this->id_nasabah;
        return Profile::find()->where(['id_user' => $id_nasabah])->one();
    }

    public function getJumlahPinjam(){
        return "Rp. ".number_format($this->nilai_pinjam,0,",",".");
    }

    public function getHargaPasar(){
        return "Rp. ".number_format($this->harga_pasar,0,",",".");
    }

    public function getPegawai(){
        return $this->hasOne(Profile::className(),['id_user'=>'created_by']);
    }

    public function myBunga(){
        $bunga = $this->nilai_pinjam * $this->bunga/100;
        return $bunga;
    }

    public function myBungaPerpanjang($sisa_hutang){
        $bunga = $sisa_hutang * $this->bunga/100;
        return $bunga;
    }

    public function myTerimabersih(){
        return $this->nilai_pinjam - ($this->myBunga() + $this->biaya_admin)-$this->biaya_simpan;
    }

    public function getHargaJual(){
        $dataJual = Jual::find()->where(['id_barang' => $this->id_barang])->one();
        $dataJual = "Rp. ".number_format($dataJual->harga_jual,0,",",".");
        return $dataJual;
    }

    public function getHargaLapor(){
        $dataJual = Jual::find()->where(['id_barang' => $this->id_barang])->one();
        $dataJual = "Rp. ".number_format($dataJual->harga_lapor,0,",",".");
        return $dataJual;
    }

    public function myTerjual(){
        $dataJual = Jual::find()->where(['id_barang' => $this->id_barang])->one();
        $sisa_kembali = $dataJual->harga_pasar - $dataJual->nilai_pinjam;
        $dataJual = ['harga_jual' => $dataJual->harga_jual,'sisa' => $sisa_kembali];

        return $dataJual;
    }

    public function getNoKontrak(){
        return "<a href=\"#\" class=\"btn-pop\" value=\"/barang/detail?id=".$this->id_barang."\">".$this->no_kontrak."</a>";
    }

    public function jumBarangAll(){
        return $this->find()->count();
    }

    public static function listCabang(){
        $datacabang = ArrayHelper::map(Cabang::find()->where(['!=', 'id_cabang', '10000'])->asArray()->all(),'id_cabang','nama_cabang');
        return $datacabang;
    }

    public function jumBarang($status){
        return $this->find()->where(['status' => $status])->count();
    }

    public function jumBarangPercabang($status,$id_cabang){
        return $this->find()->andWhere(['status' => $status, 'id_cabang' => $id_cabang])->count();
    }

    public function getCabang(){
        return $this->hasOne(Cabang::className(),['id_cabang'=>'id_cabang']);
    }

    public function getJenisBarang(){
        return $this->hasOne(JenisBarang::className(),['id_jenis_barang'=>'id_jenis']);
    }

    public function getStatusBarang(){
        return '<span class="label label-success">'.$this->status.'</span>';
    }

    public function getJual(){
        return $this->hasOne(Jual::className(),['id_barang'=>'id_barang']);
    }

    public function myDetail($sbg){
        return $this->find()->where(['no_kontrak' => $sbg])->one();
    }

    public function myCabang($id_cabang){
        return Cabang::find()->where(['id_cabang' => $id_cabang])->one();
    }

    public function myJenisBarang($sbg){
        return JenisBarang::find()->where(['id_jenis_barang' => $this->myDetail($sbg)])->one();
    }

    public function myDiskonBunga($sbg){
        $id_barang = $this->myDetail($sbg)->id_barang;
        $jangka = $this->myDetail($sbg)->jangka;
        $dataBayar = Bayar::find()->where(['id_barang' => $id_barang])->one();
        
        if(!empty($dataBayar)){
            $tgl_lunas = date_create($dataBayar->created_at);
            $tgl_masuk = date_create($this->myDetail($sbg)->tgl_masuk);
            $waktu_pinjam = date_diff($tgl_masuk,$tgl_lunas);
            $waktu_pinjam = $waktu_pinjam->format("%a");

            if($waktu_pinjam <= 15){
                if($jangka > 15){
                    $diskon_bunga = 0.05*$this->myDetail($sbg)->nilai_pinjam;
                }
                else{
                    $diskon_bunga = 0;
                }
            }
            else{
                $diskon_bunga = 0;
            }

            return $diskon_bunga;
        }
    }

    public function myNasabah2($id_nasabah){
        return Profile::find()->where(['id_user' => $id_nasabah])->one();
    }

    public function myDataLog($sbg){
        $id_barang = $this->myDetail($sbg)->id_barang;
        return LogStatus::find()->where(['id_barang' => $id_barang])->all();
    }

    public function getDenda(){
        $tgl_now = date_create(date('Y-m-d'));
        $jatuh_tempo = date_create($this->jatuh_tempo);
            $telat = date_diff($tgl_now,$jatuh_tempo);
            $telat = $telat->format("%a");
            $denda = "Rp.". number_format($telat * 5000,0,",",".");
        
        return $denda;
    }

    public function listTagihNow2(){
        $tgl_now = date('Y-m-d');
        $besok = date('Y-m-d', strtotime($tgl_now .' +1 day'));
        return $this->find()->where(['jatuh_tempo' => $besok, 'status' => 'Aktif'])->all();
    }

    public function listPasif($bunga){
        if($bunga == 5 or $bunga == 1.2){
            $lelang = '-6 day';
        }
        else{
            $lelang = '-12 day';
            //$lelang = '-6 day'; //disamakan rencananya
        }
        $tgl_now = date('Y-m-d');
        $tglLelang = date('Y-m-d', strtotime($tgl_now .$lelang));
        return $this->find()->where(['jatuh_tempo' => $tglLelang, 'bunga' => $bunga])->andWhere(['or', ['status' => 'JatuhTempo'], ['status' => 'Pasif']])->all();
    }

    public function listLelang($bunga){
        if($bunga == 5 or $bunga == 1.2){
            $lelang = '-9 day';
        }
        else{
            $lelang = '-15 day';
            //$lelang = '-9 day'; //disamakan rencananya
        }
        $tgl_now = date('Y-m-d');
        $tglLelang = date('Y-m-d', strtotime($tgl_now .$lelang));
        return $this->find()->where(['jatuh_tempo' => $tglLelang, 'bunga' => $bunga])->andWhere(['or', ['status' => 'JatuhTempo'], ['status' => 'Pasif']])->all();
    }

    public function listTagihNow($id_cabang,$jangka){
        $tgl_now = date('Y-m-d');
        $besok = date('Y-m-d', strtotime($tgl_now .' +1 day'));

common/models/Jual.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "jual".
 *
 * @property int $id_jual
 * @property int $id_barang
 * @property int $id_nasabah
 * @property int $nilai_pinjam
 * @property int $harga_pasar
 * @property int|null $harga_jual
 * @property string $status
 * @property string $created_at
 * @property int $created_by
 */
class Jual extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'jual';
    }

    /**
     * {@inheritdoc}
     */

    public function rules()
    {
        return [
            [['id_barang', 'id_nasabah', 'nilai_pinjam', 'harga_pasar', 'status', 'created_by','harga_jual'], 'required'],
            [['id_barang', 'id_nasabah', 'nilai_pinjam', 'harga_pasar', 'harga_jual', 'created_by', 'is_jurnal'], 'integer'],
            [['created_at'], 'safe'],
            [['status'], 'string', 'max' => 225],
        ];
    }

    public function cekRugi($harga_jual,$nilai_pinjam){
        if($harga_jual < $nilai_pinjam){
            return "Rugi";
        }
        else{
            return "Untung";
        }
    }

    public function getBarang(){
        return $this->hasOne(Barang::className(),['id_barang'=>'id_barang']);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_jual' => 'Id Jual',
            'id_barang' => 'Id Barang',
            'id_nasabah' => 'Id Nasabah',
            'nilai_pinjam' => 'Nilai Pinjam',
            'harga_pasar' => 'Harga Pasar',
            'harga_jual' => 'Harga Jual',
            'status' => 'Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
        ];
    }
}

backend/controllers/JualController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Jual;
use common\models\JualSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * JualController implements the CRUD actions for Jual model.
 */
class JualController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Jual models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new JualSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Jual model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Jual model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Jual();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_jual]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionFilterDataJual()
    {
        $model = new Jual();

        if ($model->load(Yii::$app->request->post())) {
            $tgl = explode(" - ",$model->created_at);
            $date1=trim($tgl[0]);
            $date2=trim($tgl[1]);

            $dataJual = $model->find()->where(['between', 'created_at', $date1, $date2])->all();

            return $this->render('data-jual', [
                'dataJual' => $dataJual,
                'date1' => $date1,
                'date2' => $date2
            ]);
        }

        return $this->render('filter-data-jual', [
            'model' => $model,
        ]);
    }

    public function actionPrintDataJual($date1,$date2){

        $dataJual = Jual::find()->where(['between', 'created_at', $date1, $date2])->all();

        return $this->renderAjax('print-data-jual', [
            'dataJual' => $dataJual,
            'date1' => $date1,
            'date2' => $date2
        ]);
    }
    

    /**
     * Updates an existing Jual model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_jual]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Jual model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Jual model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Jual the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Jual::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/jual/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Jual */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="jual-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_barang')->textInput() ?>

    <?= $form->field($model, 'id_nasabah')->textInput() ?>

    <?= $form->field($model, 'nilai_pinjam')->textInput() ?>

    <?= $form->field($model, 'harga_pasar')->textInput() ?>

    <?= $form->field($model, 'harga_jual')->textInput() ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/jual/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\JualSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="jual-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_jual') ?>

    <?= $form->field($model, 'id_barang') ?>

    <?= $form->field($model, 'id_nasabah') ?>

    <?= $form->field($model, 'nilai_pinjam') ?>

    <?= $form->field($model, 'harga_pasar') ?>

    <?php // echo $form->field($model, 'harga_jual') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/jual/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Jual */

$this->title = 'Create Jual';
$this->params['breadcrumbs'][] = ['label' => 'Juals', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jual-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/jual/data-jual.php
<?php

use yii\helpers\Html;

$this->title = "Data Penjualan Barang";

?>
<div class="box box-success">
    <div class="box-header">
        <h3 align="center">
            Data Barang Terjual
        </h3>
        <hr>
    </div>
    <div class="box-body">
        <table class="table table-hover table-striped table-responsive">
            <thead>
                <tr>
                    <th rowspan="2">No.</th>
                    <th rowspan="2">SBG</th>
                    <th rowspan="2">Nama Nasabah</th>
                    <th rowspan="2">KTP</th>
                    <th rowspan="2">Type</th>
                    <th rowspan="2">Nama Barang</th>
                    <th rowspan="2">Sisa Pinjam</th>
                    <th colspan="5">Rincian Penjualan</th>
                    <th rowspan="2">Total Harga</th>
                </tr>
                <tr>
                    <th>Kerugian</th>
                    <th>Bunga</th>
                    <th>Denda</th>
                    <th>Laba</th>
                    <th>Kelebihan</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    $no = 1;
                    $tSisaPinjam = 0;
                    $tKerugian = 0;
                    $tBunga = 0;
                    $tDenda = 0;
                    $tLaba = 0;
                    $tKelebihan = 0;
                    $tTotalHarga = 0 ;
                    foreach($dataJual as $jual){
                        $barang = $jual->barang;
                        $sisaPinjam = $barang->sisapinjam2;
                        $tSisaPinjam += $sisaPinjam;

                        if(!$barang->getJurnalJuals()){
                            $kerugian = 0;
                            $bunga = 0;
                            $denda = 0;
                            $laba = 0;
                            $kelebihan = 0;
                        }
                        else{
                            $kerugian = $barang->getJurnalJuals()->andWhere(['akun_id' => 5015])->sum('jumlah_uang');
                            $bunga = $barang->getJurnalJuals()->andWhere(['akun_id' => 4017])->sum('jumlah_uang');
                            $denda = $barang->getJurnalJuals()->andWhere(['akun_id' => 4018])->sum('jumlah_uang');
                            $laba = $barang->getJurnalJuals()->andWhere(['akun_id' => 4019])->sum('jumlah_uang');
                            $kelebihan = $barang->getJurnalJuals()->andWhere(['akun_id' => 2109])->sum('jumlah_uang');

                            $totalHarga = $sisaPinjam - $kerugian + $bunga + $denda + $laba + $kelebihan;
                        }

                        $tKerugian += $kerugian;
                        $tBunga += $bunga;
                        $tDenda += $denda;
                        $tLaba += $laba;
                        $tKelebihan += $kelebihan;
                        $tTotalHarga += $totalHarga;


                ?>
                <tr>
                    <td><?= $no++; ?></td>
                    <td><?= $barang->no_kontrak; ?></td>
                    <td><?= $barang->nasabah->nama; ?></td>
                    <td><?= $barang->nasabah->no_ktp; ?></td>
                    <td><?= $barang->merk." - ".$barang->tipe; ?></td>
                    <td><?= $barang->nama_barang; ?></td>
                    <td><?= Yii::$app->formatter->asInteger($sisaPinjam); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($kerugian); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($bunga); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($denda); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($laba); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($kelebihan); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($totalHarga); ?></td>
                </tr>
                <?php } ?>
                <tr>
                    <td colspan="6">TOTAL : </td>
                    <td><?= Yii::$app->formatter->asInteger($tSisaPinjam); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($tKerugian); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($tBunga); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($tDenda); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($tLaba); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($tKelebihan); ?></td>
                    <td><?= Yii::$app->formatter->asInteger($tTotalHarga); ?></td>
                </tr>
            </tbody>
        </table>

        <?= Html::a('<span class="fa fa-table"></span> Export ',['print-data-jual', 'date1' => $date1, 'date2' => $date2], ['class' => 'btn btn-info btn-block', 'target' => '_blank']); ?>

    </div>
</div>

backend/views/jual/print-data-jual.php
<?php
header('Content-type: application/vnd-ms-excel');
header('Content-Disposition: attachment; filename=data-penjualan.xls');
?>
<div class="box box-success">
    <div class="box-header">
        <h3 align="center">
            Data Barang Terjual
        </h3>
        <hr>
    </div>
    <div class="box-body">
        <table class="table table-hover table-striped table-responsive">
            <thead>
                <tr>
                    <th rowspan="2">No.</th>
                    <th rowspan="2">SBG</th>
                    <th rowspan="2">Nama Nasabah</th>
                    <th rowspan="2">KTP</th>
                    <th rowspan="2">Type</th>
                    <th rowspan="2">Nama Barang</th>
                    <th rowspan="2">Sisa Pinjam</th>
                    <th colspan="5">Rincian Penjualan</th>
                    <th rowspan="2">Total Harga</th>
                </tr>
                <tr>
                    <th>Kerugian</th>
                    <th>Bunga</th>
                    <th>Denda</th>
                    <th>Laba</th>
                    <th>Kelebihan</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    $no = 1;
                    $tSisaPinjam = 0;
                    $tKerugian = 0;
                    $tBunga = 0;
                    $tDenda = 0;
                    $tLaba = 0;
                    $tKelebihan = 0;
                    $tTotalHarga = 0 ;
                    foreach($dataJual as $jual){
                        $barang = $jual->barang;
                        $sisaPinjam = $barang->sisapinjam2;
                        $tSisaPinjam += $sisaPinjam;

                        if(!$barang->getJurnalJuals()){
                            $kerugian = 0;
                            $bunga = 0;
                            $denda = 0;
                            $laba = 0;
                            $kelebihan = 0;
                        }
                        else{
                            $kerugian = $barang->getJurnalJuals()->andWhere(['akun_id' => 5015])->sum('jumlah_uang');
                            $bunga = $barang->getJurnalJuals()->andWhere(['akun_id' => 4017])->sum('jumlah_uang');
                            $denda = $barang->getJurnalJuals()->andWhere(['akun_id' => 4018])->sum('jumlah_uang');
                            $laba = $barang->getJurnalJuals()->andWhere(['akun_id' => 4019])->sum('jumlah_uang');
                            $kelebihan = $barang->getJurnalJuals()->andWhere(['akun_id' => 2109])->sum('jumlah_uang');

                            $totalHarga = $sisaPinjam - $kerugian + $bunga + $denda + $laba + $kelebihan;
                        }

                        $tKerugian += $kerugian;
                        $tBunga += $bunga;
                        $tDenda += $denda;
                        $tLaba += $laba;
                        $tKelebihan += $kelebihan;
                        $tTotalHarga += $totalHarga;


                ?>
                <tr>
                    <td><?= $no++; ?></td>
                    <td><?= $barang->no_kontrak; ?></td>
                    <td><?= $barang->nasabah->nama; ?></td>
                    <td><?= "'".$barang->nasabah->no_ktp; ?></td>
                    <td><?= $barang->merk." - ".$barang->tipe; ?></td>
                    <td><?= $barang->nama_barang; ?></td>
                    <td><?= $sisaPinjam; ?></td>
                    <td><?= $kerugian; ?></td>
                    <td><?= $bunga; ?></td>
                    <td><?= $denda; ?></td>
                    <td><?= $laba; ?></td>
                    <td><?= $kelebihan; ?></td>
                    <td><?= $totalHarga; ?></td>
                </tr>
                <?php } ?>
                <tr>
                    <td colspan="6">TOTAL : </td>
                    <td><?= $tSisaPinjam; ?></td>
                    <td><?= $tKerugian; ?></td>
                    <td><?= $tBunga; ?></td>
                    <td><?= $tDenda; ?></td>
                    <td><?= $tLaba; ?></td>
                    <td><?= $tKelebihan; ?></td>
                    <td><?= $tTotalHarga; ?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

backend/views/jual/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Jual */

$this->title = 'Update Jual: ' . $model->id_jual;
$this->params['breadcrumbs'][] = ['label' => 'Juals', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_jual, 'url' => ['view', 'id' => $model->id_jual]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="jual-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>